version: '3.3'

services:
  db:
    build:
      context: .  # Set the build context to the project root
      dockerfile: docker/Dockerfile  # Reference the Dockerfile in the 'docker' directory
    image: mypostgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2022
      - POSTGRES_DB=odoo16
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
        - odoo-network

  odoo16:
    build:
      context: .  # Set the build context to the project root
      dockerfile: docker/Dockerfile  # Reference the Dockerfile in the 'docker' directory
    image: myodoo:16
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072"  # live chat
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo16@2022
      - ODOO_CONF=/etc/odoo/odoo.conf
    volumes:
      - ./addons:/mnt/extra-addons
      - ./update_module_list.py:/scripts/update_module_list.py
      - ./etc:/etc/odoo
      - ./scripts:/scripts
    entrypoint: >
      bash -c "
      /scripts/wait-for-it.sh db:5432 -- python3 /scripts/update_module_list.py &&
      /entrypoint.sh odoo"
    restart: always
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge
