version: "3.8"
services:
  odoo:
    image: ${{ secrets.DOCKER_USERNAME }}/od:latest
    environment:
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo16
    ports:
      - "8069:8069" # Expose port 8069 to the host
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo16
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo"]
      interval: 5s
      timeout: 10s
      retries: 5
