version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo  # PostgreSQL username
      POSTGRES_PASSWORD: odoo16@2022  # PostgreSQL password
      POSTGRES_DB: odoo16  # Default database
      PGDATA: /var/lib/postgresql/data  # Data directory
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]  # Check database readiness
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - odoo-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  odoo16:
    image: myodoo:16
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy  # Wait for PostgreSQL to be ready
    ports:
      - "10016:8069"  # Odoo web interface
      - "20016:8072"  # Odoo longpolling service
    environment:
      DB_HOST: db  # PostgreSQL host
      DB_PORT: 5432  # PostgreSQL port
      DB_USER: odoo  # PostgreSQL username
      DB_PASSWORD: odoo16@2022  # PostgreSQL password
      DB_NAME: odoo16  # Default Odoo database
      ODOO_CONF: /etc/odoo/odoo.conf  # Odoo configuration file
    volumes:
      - ./addons:/mnt/extra-addons  # Custom addons directory
      - ./update_module_list.py:/scripts/update_module_list.py  # Update script
      - ./etc:/etc/odoo  # Configuration files
      - ./scripts:/scripts  # Custom scripts
      - ./logs:/var/log/odoo  # Logs directory
    entrypoint: >
      bash -c "
      /scripts/wait-for-it.sh db:5432 --timeout=60 &&
      /entrypoint.sh odoo -d odoo16 -i base --stop-after-init &&
      /entrypoint.sh odoo"
    networks:
      - odoo-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G  # Memory limit
          cpus: "1.0"  # CPU limit

volumes:
  postgres_data: {}  # Persistent volume for PostgreSQL

networks:
  odoo-network:
    driver: bridge  # Network driver
