version: '3.7'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo16@2022
      POSTGRES_DB: odoo16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network
    restart: unless-stopped

  odoo16:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: myodoo:16
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072"
    tty: true
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo16@2022
      DB_NAME: odoo16
      ODOO_CONF: /etc/odoo/odoo.conf
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./scripts:/scripts
    entrypoint: >
      bash -c "
      /scripts/wait-for-it.sh db:5432 --timeout=60 &&
      python3 /scripts/update_module_list.py &&
      /entrypoint.sh odoo"
    restart: unless-stopped
    networks:
      - odoo-network

volumes:
  postgres_data: {}

networks:
  odoo-network:
    driver: bridge
