# Use the official PostgreSQL image as the base
FROM postgres:15

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=odoo
ENV POSTGRES_PASSWORD=odoo16@2022
ENV POSTGRES_DB=postgres

# Expose the PostgreSQL port
EXPOSE 5432
