name: CI/CD for Odoo with PostgreSQL

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t alexitmcaf/myodoo:16 -f docker/Dockerfile .

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag myodoo:16 alexitmcaf/myodoo:latest
          docker push alexitmcaf/myodoo:latest

      - name: Start Docker Compose for Tests
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for PostgreSQL to be Ready
        run: |
          for i in {1..10}; do
            docker exec $(docker ps -q -f name=db) pg_isready -U odoo && break
            echo "PostgreSQL not ready, retrying in 10s..."
            sleep 5
          done
          docker exec $(docker ps -q -f name=db) pg_isready -U odoo || exit 1

      - name: Test Odoo Service
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:10016; then
              echo "Odoo is up and running!"
              break
            fi
            echo "Waiting for Odoo to start..."
            sleep 5
          done

          if ! curl -f http://localhost:10016; then
            echo "Odoo failed to start. Check logs."
            exit 1
          fi

      - name: Debug Odoo Logs
        run: |
          docker logs $(docker ps -q -f name=odoo16)

      - name: Tear Down Docker Compose
        run: docker-compose down
