name: CI/CD for Odoo with Custom PostgreSQL

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: List Running Containers
        run: docker ps -a

      - name: Wait for PostgreSQL
        run: |
          for i in {1..20}; do
            docker exec $(docker ps -q -f name=db) pg_isready -U odoo && break
            echo "Waiting for PostgreSQL to be ready..."
            sleep 10
          done

      - name: Create Odoo Database if Not Exists
        run: |
          docker exec $(docker ps -q -f name=db) psql -U odoo -d postgres -c "SELECT 1 FROM pg_database WHERE datname='odoo16';" | grep -q 1 || \
          docker exec $(docker ps -q -f name=db) psql -U odoo -d postgres -c "CREATE DATABASE odoo16;"

      - name: Debug PostgreSQL
        run: |
          docker exec $(docker ps -q -f name=db) psql -U odoo -d postgres -c "\l"

      - name: Wait for Odoo
        run: |
          for i in {1..20}; do
            if curl -f http://localhost:10016; then
              echo "Odoo is ready!"
              break
            fi
            echo "Retrying in 10 seconds..."
            sleep 10
          done

      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.test.yml down
