name: CI/CD for Odoo with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load Environment Variables
        run: echo "Loading environment variables from .env"

      - name: Validate Configuration
        run: |
          test -f docker-compose.test.yml || (echo "Missing docker-compose.test.yml" && exit 1)
          test -f docker/Dockerfile || (echo "Missing Dockerfile" && exit 1)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Image
        run: |
          docker build -t alexitmcaf/myodoo:${{ github.sha }} -f docker/Dockerfile .

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag alexitmcaf/myodoo:${{ github.sha }} alexitmcaf/myodoo:latest
          docker push alexitmcaf/myodoo:${{ github.sha }}
          docker push alexitmcaf/myodoo:latest

      - name: Start Docker Compose for Tests
        run: |
          docker-compose -f docker-compose.test.yml up -d --build

      - name: Wait for PostgreSQL to be Ready
        run: |
          for i in {1..30}; do
            docker exec $(docker ps -q -f name=db) pg_isready -U odoo && break
            echo "PostgreSQL not ready, retrying in 10s..."
            sleep 10
          done
          docker exec $(docker ps -q -f name=db) pg_isready -U odoo || exit 1

      - name: Debug PostgreSQL Logs
        run: docker logs $(docker ps -q -f name=db)

      - name: Test Odoo Service
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:10016/web; then
              echo "Odoo /web endpoint is up!"
              break
            fi
            echo "Waiting for Odoo to start..."
            sleep 10
          done

          if ! curl -f http://localhost:10016/web; then
            echo "Odoo failed to start. Check logs."
            exit 1
          fi

      - name: Debug Odoo Logs
        run: docker logs $(docker ps -q -f name=odoo16)

      - name: Check Database State
        run: |
          docker exec $(docker ps -q -f name=db) psql -U odoo -d odoo16 -c '\dt'

      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose -f docker-compose.test.yml down

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: debug-logs
          path: logs/
