name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker cache
      id: docker-cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
                            --cache-to=type=local,dest=/tmp/.buildx-cache \
                            --push \
                            -t ${{ secrets.DOCKER_USERNAME }}/odoo:16 ./docker

    # - name: Deploy to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy Docker Compose to Azure
    #   run: |
    #     az containerapp up --name odoo16 \
    #       --resource-group myResourceGroup \
    #       --image ${{ secrets.DOCKER_USERNAME }}/odoo:16 \
    #       --environment-variables POSTGRES_USER=odoo POSTGRES_PASSWORD=odoo16@2022
