name: CI/CD for Odoo with Custom PostgreSQL

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify addons directory
        run: test -d ./addons || { echo "addons directory not found"; exit 1; }

      - name: Verify odoo.conf file
        run: test -f ./etc/odoo.conf || { echo "odoo.conf file not found"; exit 1; }

      - name: Copy addons and odoo.conf to docker folder
        run: |
          mkdir -p docker/addons
          mkdir -p docker/etc
          cp -r ./addons/* ./docker/addons/
          cp ./etc/odoo.conf ./docker/etc/odoo.conf

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Odoo Docker image
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/od:latest,${{ secrets.DOCKER_USERNAME }}/od:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/od:cache
          cache-to: type=inline

      - name: Test Docker Image
        run: |
          docker run --rm -d -p 8069:8069 ${{ secrets.DOCKER_USERNAME }}/od:latest
          sleep 10
          curl -f http://localhost:8069 || { echo "Odoo failed to start"; exit 1; }
